PACKS = {
    "CAT-00": {"name": "Moltz Expert", "sub_attenuation": "halved", "main_only": False},
    "CAT-01": {"name": "Item Expert", "sub_attenuation": "halved", "main_only": False},
    "CAT-02": {"name": "Goliath", "sub_attenuation": "halved_multiplier", "main_only": False},
    "CAT-03": {"name": "Thorns", "sub_attenuation": "halved_no_def_bonus", "main_only": False},
    "CAT-04": {"name": "Scout", "sub_attenuation": None, "main_only": True},
    "CAT-05": {"name": "Ruin Expert", "sub_attenuation": "none", "main_only": False},
    "CAT-06": {"name": "Berserker", "sub_attenuation": "reduced", "main_only": False},
    "CAT-07": {"name": "Double Attack", "sub_attenuation": "reduced", "main_only": False},
    "CAT-08": {"name": "Heart of the Giant", "sub_attenuation": "halved", "main_only": False},
    "CAT-09": {"name": "Bomber", "sub_attenuation": "halved", "main_only": False},
    "CAT-10": {"name": "Trail Ward", "sub_attenuation": "reduced", "main_only": False},
    "CAT-11": {"name": "Ranged", "sub_attenuation": "extra_ep", "main_only": False},
    "CAT-12": {"name": "Sword Master", "sub_attenuation": "reduced", "main_only": False},
    "CAT-13": {"name": "Duelist", "sub_attenuation": "halved", "main_only": False},
    "CAT-14": {"name": "Raider", "sub_attenuation": "extra_ep", "main_only": False},
    "CAT-15": {"name": "Last Stand", "sub_attenuation": "reduced", "main_only": False},
    "CAT-16": {"name": "Iron Heart", "sub_attenuation": "halved", "main_only": False},
    "CAT-17": {"name": "Sunflame Cloak", "sub_attenuation": "halved", "main_only": False},
    "CAT-18": {"name": "Assassin", "sub_attenuation": None, "main_only": True},
    "CAT-19": {"name": "Pickpocket", "sub_attenuation": "extra_ep", "main_only": False}
}